
INSERT INTO packages (id, category_id, destination_id, slug, title, subtitle, overview, duration_days, duration_nights, starting_price, tour_type, is_featured, is_published, cover_image, gallery, highlights, inclusions, exclusions, itinerary, pricing)
VALUES
-- 1. Tirupati Balaji 3D/2N
('a0011001-0000-4000-8000-000000000001', '11111111-0001-0001-0001-000000000001', 'b1d00001-0000-4000-8000-000000000001',
 'tirupati-balaji-3d2n', 'Tirupati Balaji Darshan', 'Sacred 3 Days / 2 Nights Pilgrimage',
 'Experience the divine blessings of Lord Venkateswara at Tirupati. Our expertly crafted package ensures a seamless darshan with VIP access, comfortable accommodation, and all temple rituals covered.',
 3, 2, 4999, 'pilgrimage', true, true,
 'https://images.pexels.com/photos/2161449/pexels-photo-2161449.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2161449/pexels-photo-2161449.jpeg?auto=compress&cs=tinysrgb&w=800','https://images.pexels.com/photos/3881104/pexels-photo-3881104.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['VIP Darshan at Tirumala','Kalyanakatta Hair Tonsuring','Arjitha Sevas booking','Prasadam included','Air-conditioned accommodation'],
 ARRAY['AC accommodation for 2 nights','All transportation by AC vehicle','VIP darshan tickets','Daily breakfast and dinner','Expert pilgrim guide'],
 ARRAY['Airfare / train tickets','Personal expenses','Camera charges inside temple','Laddu prasadam charges'],
 '[{"day":1,"title":"Arrival & Check-in","description":"Arrive at Tirupati, check in to hotel, evening visit Govindaraja Swamy Temple and Sri Padmavathi Ammavari Temple at Tiruchanur."},{"day":2,"title":"Tirumala Darshan","description":"Early morning travel to Tirumala hills. VIP darshan of Lord Venkateswara, Kalyanakatta, Akasha Ganga, Papavinasam theertham. Evening return to Tirupati."},{"day":3,"title":"Local Temples & Departure","description":"Visit Kapila Theertham, Srinivasamangapuram, Sri Venkateswara National Park. Post lunch, departure transfer."}]',
 '[{"type":"standard","label":"Standard Package (Per Person)","amount":4999},{"type":"deluxe","label":"Deluxe Package (Per Person)","amount":6999},{"type":"couple","label":"Couple Package","amount":9499}]'),

-- 2. Rameswaram Kanyakumari 4D/3N
('a0011002-0000-4000-8000-000000000002', '11111111-0001-0001-0001-000000000001', 'ff000003-0000-4000-8000-000000000003',
 'rameswaram-kanyakumari-4d3n', 'Rameswaram & Kanyakumari Tour', 'Sacred South India 4 Days / 3 Nights',
 'A spiritually enriching journey to the southernmost tip of India. Visit the magnificent Ramanathaswamy Temple, witness the confluence of three seas at Kanyakumari, and be blessed by the divine.',
 4, 3, 6999, 'pilgrimage', true, true,
 'https://images.pexels.com/photos/3573351/pexels-photo-3573351.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/3573351/pexels-photo-3573351.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['22 sacred theerthams at Ramanathaswamy','Floating stone bridge — Rama Setu','Vivekananda Rock Memorial','Sunrise at Kanyakumari','Padmanabhapuram Palace visit'],
 ARRAY['3 nights AC accommodation','All meals (breakfast & dinner)','AC vehicle throughout','Temple entry arrangements','Expert guide'],
 ARRAY['Train/flight tickets','Personal shopping','Camera fees'],
 '[{"day":1,"title":"Chennai to Rameswaram","description":"Depart Chennai early morning. Arrive Rameswaram by afternoon. Check in, evening visit Ramanathaswamy Temple outer prakarams."},{"day":2,"title":"Rameswaram Full Day","description":"Early morning temple darshan with all 22 theerthams. Visit Dhanushkodi, Pamban Bridge, Kothandaramaswamy Temple."},{"day":3,"title":"Rameswaram to Kanyakumari","description":"Depart after breakfast. En route visit Thiruchendur Murugan Temple. Arrive Kanyakumari, sunset at the Triveni Sangam."},{"day":4,"title":"Kanyakumari & Departure","description":"Sunrise darshan, Vivekananda Rock Memorial, Thiruvalluvar Statue, Kumari Amman Temple. Depart for Chennai."}]',
 '[{"type":"standard","label":"Per Person (Twin Sharing)","amount":6999},{"type":"deluxe","label":"Deluxe (Per Person)","amount":8999}]'),

-- 3. Navagraha Temples
('a0011003-0000-4000-8000-000000000003', '11111111-0001-0001-0001-000000000001', 'd0010065-0000-4000-8000-000000000065',
 'navagraha-temples-2d1n', 'Navagraha Temples Circuit', 'Astrological Remedy Tour 2 Days / 1 Night',
 'Visit all 9 Navagraha temples in Tamil Nadu in a spiritually powerful circuit tour. Seek blessings from all nine planetary deities to nullify doshas and bring peace, prosperity, and planetary harmony.',
 2, 1, 3499, 'pilgrimage', false, true,
 'https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['All 9 Navagraha temples in one circuit','Expert astrologer-guide','Special poojas arranged','Kumbakonam base stay','Prasadam at each temple'],
 ARRAY['1 night accommodation at Kumbakonam','Breakfast and dinner','AC vehicle for temple circuit','Pooja arrangements','Astrologer guide'],
 ARRAY['Special abhishekam charges','Personal expenses'],
 '[{"day":1,"title":"Suryan to Chandran","description":"Begin at Suryanar Kovil (Surya), Thingaloor (Chandra), Thiruvengadu (Budha), Keezhperumpallam (Kethu). Lunch and check-in at Kumbakonam."},{"day":2,"title":"Remaining Navagrahams & Departure","description":"Visit Alangudi (Guru), Kanjanur (Sukra), Thirunallar (Sani), Vaitheeswaran Koil (Angaraka), Keezhaperumpallam (Rahu). Depart post lunch."}]',
 '[{"type":"standard","label":"Per Person","amount":3499},{"type":"couple","label":"Couple Package","amount":6499}]'),

-- 4. Palani Day Trip
('a0011004-0000-4000-8000-000000000004', '11111111-0001-0001-0001-000000000001', 'd0010001-0000-4000-8000-000000000001',
 'palani-murugan-1d', 'Palani Murugan Day Trip', 'Blessed Pilgrimage Day Excursion',
 'A one-day divine journey to Palani, one of the six abodes of Lord Murugan. Ascend the sacred hill via ropeway and seek the blessings of Lord Dhandayudhapani Swamy.',
 1, 0, 1299, 'pilgrimage', false, true,
 'https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Ropeway to hilltop temple','Kavadi procession witnessing','Panchamritham prasadam','Scenic hill views','Comfortable AC vehicle'],
 ARRAY['AC vehicle from Coimbatore/Chennai','Ropeway tickets','Temple prasadam','Expert guide'],
 ARRAY['Meals — stop at restaurant en route','Personal expenses'],
 '[{"day":1,"title":"Palani Darshan","description":"Early morning departure, arrive Palani by 9am. Ropeway ride to hilltop, darshan at Dhandayudhapani Temple, visit Idumban shrine. Return by evening."}]',
 '[{"type":"standard","label":"Per Person","amount":1299},{"type":"group","label":"Group (4+ pax per head)","amount":999}]'),

-- 5. Char Dham Yatra 11D/10N
('a0011005-0000-4000-8000-000000000005', '11111111-0001-0001-0001-000000000001', 'd0010079-0000-4000-8000-000000000079',
 'char-dham-yatra-11d10n', 'Char Dham Yatra 2025', 'Badrinath Kedarnath Gangotri Yamunotri — 11 Days',
 'The ultimate Himalayan pilgrimage — visit all four sacred dhams in one spiritually transformative journey. Experience the magnificence of the Himalayas and attain moksha through these sacred shrines.',
 11, 10, 24999, 'pilgrimage', true, true,
 'https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=800','https://images.pexels.com/photos/1366957/pexels-photo-1366957.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['All 4 Char Dhams covered','Helicopter option available','Experienced Himalayan guide','Medical kit & oxygen support','Comfortable mountain lodges'],
 ARRAY['10 nights accommodation','All meals (breakfast, lunch, dinner)','AC vehicle Haridwar to Haridwar','Experienced mountaineer guide','Pony/palanquin arrangements','Medical emergency support'],
 ARRAY['Airfare/train to Haridwar','Helicopter upgrades','Personal expenses','Porter charges'],
 '[{"day":1,"title":"Arrival Haridwar","description":"Arrive Haridwar, check-in. Evening Ganga Aarti at Har Ki Pauri. Orientation briefing."},{"day":2,"title":"Haridwar to Barkot","description":"Drive to Barkot via Mussoorie and Chamba. Check-in and rest."},{"day":3,"title":"Yamunotri Dham","description":"Trek/pony to Yamunotri shrine. Dip in Jamunabai Kund, darshan at Yamunotri Temple. Return Barkot."},{"day":4,"title":"Barkot to Uttarkashi","description":"Drive to Uttarkashi. Visit Vishwanath Temple. Overnight stay."},{"day":5,"title":"Gangotri Dham","description":"Drive to Gangotri. Darshan at Gangotri Temple. Evening aarti. Overnight Gangotri."},{"day":6,"title":"Gangotri to Guptkashi","description":"Drive to Guptkashi via Tehri Dam. Check-in. Visit Ardhnarishwar Temple."},{"day":7,"title":"Kedarnath Dham","description":"Trek/helicopter to Kedarnath. Darshan at Kedarnath Temple. Evening abhishekam. Overnight Kedarnath."},{"day":8,"title":"Kedarnath to Badrinath","description":"Trek down, drive to Badrinath via Joshimath. Check-in at Badrinath."},{"day":9,"title":"Badrinath Dham","description":"Early morning darshan at Badrinath Temple. Mana Village, Vyas Gufa, Bhim Pul. Evening aarti."},{"day":10,"title":"Badrinath to Rishikesh","description":"Drive to Rishikesh. Evening at leisure. Visit Triveni Ghat."},{"day":11,"title":"Rishikesh to Haridwar Departure","description":"Morning Ganga snaan, visit Lakshman Jhula. Transfer to Haridwar for departure."}]',
 '[{"type":"standard","label":"Per Person (Twin Sharing)","amount":24999},{"type":"deluxe","label":"Deluxe (Per Person)","amount":34999},{"type":"helicopter","label":"With Helicopter (Per Person)","amount":54999}]'),

-- 6. Varanasi Allahabad
('a0011006-0000-4000-8000-000000000006', '11111111-0001-0001-0001-000000000001', 'ff000001-0000-4000-8000-000000000001',
 'varanasi-allahabad-5d4n', 'Varanasi & Prayagraj Pilgrimage', 'Kashi Vishwanath Ganga Ghat Triveni Sangam — 5 Days',
 'Embark on a soul-stirring journey to the ancient city of Varanasi and the sacred Prayagraj. Witness the magnificent Ganga Aarti, take a holy dip at Triveni Sangam, and seek blessings at Kashi Vishwanath.',
 5, 4, 9999, 'pilgrimage', true, true,
 'https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Kashi Vishwanath Temple VIP darshan','Ganga Aarti at Dashashwamedh Ghat','Boat ride on River Ganga','Holy dip at Triveni Sangam','Sarnath Buddhist Circuit'],
 ARRAY['4 nights accommodation','Daily breakfast and dinner','AC vehicle throughout','Expert guide','Boat ride arrangements'],
 ARRAY['Train/flight tickets','Personal puja samagri','Camera charges at ghats'],
 '[{"day":1,"title":"Arrival Varanasi","description":"Arrive Varanasi, check-in. Evening Ganga Aarti boat ride at Dashashwamedh Ghat."},{"day":2,"title":"Varanasi Temples","description":"Dawn boat ride, Kashi Vishwanath Temple darshan (VIP), Annapurna Temple, Manikarnika Ghat. Afternoon Sarnath Buddhist Circuit."},{"day":3,"title":"Varanasi Local Sightseeing","description":"Ramnagar Fort, Durga Temple, Tulsi Manas Temple, Bharat Mata Temple. Evening ghats walk."},{"day":4,"title":"Prayagraj Triveni Sangam","description":"Drive to Prayagraj. Boat ride at Triveni Sangam, Allahabad Fort, Hanuman Temple, Anand Bhavan."},{"day":5,"title":"Prayagraj to Departure","description":"Morning: Akshayavat, Saraswati Koop. Transfer to Varanasi airport/station for departure."}]',
 '[{"type":"standard","label":"Per Person (Twin Sharing)","amount":9999},{"type":"deluxe","label":"Deluxe Per Person","amount":13999}]'),

-- 7. Shirdi Sai Baba
('a0011007-0000-4000-8000-000000000007', '11111111-0001-0001-0001-000000000001', 'ff000004-0000-4000-8000-000000000004',
 'shirdi-sai-baba-3d2n', 'Shirdi Sai Baba Darshan', 'Divine Blessings at Shirdi — 3 Days / 2 Nights',
 'Seek the divine blessings of Sai Baba at his sacred abode in Shirdi. Our package covers all major temples, comfortable stay near the temple complex, and guided darshan assistance.',
 3, 2, 5499, 'pilgrimage', false, true,
 'https://images.pexels.com/photos/3571111/pexels-photo-3571111.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/3571111/pexels-photo-3571111.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Sai Baba main temple darshan','Dwarkamai Masjid visit','Chawdi and Gurusthan','Shani Shingnapur excursion','Comfortable temple-adjacent stay'],
 ARRAY['2 nights accommodation','Breakfast and dinner daily','AC vehicle','Temple entry assistance','Guide'],
 ARRAY['Flight/train to Shirdi/Pune','Personal expenses','Prasadam charges'],
 '[{"day":1,"title":"Arrival First Darshan","description":"Arrive Shirdi/Pune, transfer to Shirdi. Check-in near temple. Evening darshan at Sai Baba Samadhi Mandir."},{"day":2,"title":"Full Day Shirdi Darshan","description":"Morning aarti darshan. Visit Dwarkamai, Chawdi, Gurusthan, Lendi Baug, Shri Sathe Wada. Afternoon Shani Shingnapur excursion."},{"day":3,"title":"Morning Darshan Departure","description":"Early morning darshan, receive prasadam. Breakfast. Depart for airport/station."}]',
 '[{"type":"standard","label":"Per Person","amount":5499},{"type":"couple","label":"Couple Package","amount":10499}]'),

-- 8. Guruvayur Sabarimala
('a0011008-0000-4000-8000-000000000008', '11111111-0001-0001-0001-000000000001', 'd0010002-0000-4000-8000-000000000002',
 'guruvayur-sabarimala-5d4n', 'Guruvayur & Sabarimala Package', 'Kerala Sacred Circuit — 5 Days / 4 Nights',
 'A blessed pilgrimage combining the two most sacred shrines of Kerala — the ancient Guruvayur Krishna Temple and the forest-clad Sabarimala Ayyappa Shrine.',
 5, 4, 11999, 'pilgrimage', false, true,
 'https://images.pexels.com/photos/2387416/pexels-photo-2387416.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2387416/pexels-photo-2387416.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Guruvayur Devaswom darshan','Sabarimala Ayyappa trek','Chakkulathukavu Devi Temple','Mammiyur Shiva Temple','Traditional vegetarian meals'],
 ARRAY['4 nights accommodation','All vegetarian meals','AC vehicle','Trek guide to Sabarimala','All pilgrimage arrangements'],
 ARRAY['Train/flight to Kerala','Irumudi kit charges','Personal expenses'],
 '[{"day":1,"title":"Arrive Guruvayur","description":"Arrive Thrissur/Kochi, drive to Guruvayur. Check-in, evening darshan at Guruvayur Sri Krishna Temple."},{"day":2,"title":"Guruvayur Full Day","description":"Morning darshan (4am oottu), Mammiyur Shiva Temple, Chakkulathukavu Devi Temple, elephant yard. Evening Krishnanattam performance."},{"day":3,"title":"Guruvayur to Pampa Base","description":"Drive to Pampa. Pampa river holy dip, base camp setup, trek begins for Sabarimala."},{"day":4,"title":"Sabarimala Ayyappa Darshan","description":"Complete the sacred trek, darshan at Sabarimala temple, Malikappuram Devi, 18 Holy Steps. Return to Pampa base."},{"day":5,"title":"Departure","description":"Drive from Pampa, breakfast en route, transfer to Kochi/Thrissur for departure."}]',
 '[{"type":"standard","label":"Per Person","amount":11999},{"type":"group","label":"Group Rate (5+ pax)","amount":9999}]'),

-- 9. Pancha Bhuta Stalas
('a0011009-0000-4000-8000-000000000009', '11111111-0001-0001-0001-000000000001', 'd0010007-0000-4000-8000-000000000007',
 'pancha-bhuta-stalas-4d3n', 'Pancha Bhuta Stalas Circuit', 'Five Element Shiva Temples — 4 Days / 3 Nights',
 'Worship at all five elemental Shiva temples representing earth, water, fire, air, and space. A rare and complete circuit of Tamil Nadu and Andhra Pradesh''s most ancient Shiva shrines.',
 4, 3, 7999, 'pilgrimage', false, true,
 'https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Ekambreshwarar Kanchipuram — Earth','Jambukeshwara Trichy — Water','Annamalaiyar Tiruvannamalai — Fire','Srikalahasti — Air','Chidambaram Nataraja — Space'],
 ARRAY['3 nights accommodation','Breakfast and dinner','AC vehicle','Temple guide at each shrine'],
 ARRAY['Train/flight','Personal expenses','Special abhishekam'],
 '[{"day":1,"title":"Kanchipuram & Trichy","description":"Begin at Ekambreshwarar Temple, Kanchipuram (Earth). Afternoon drive to Trichy — Jambukeshwara Temple (Water). Overnight Trichy."},{"day":2,"title":"Tiruvannamalai","description":"Drive to Tiruvannamalai — Annamalaiyar Temple (Fire). Overnight Tiruvannamalai."},{"day":3,"title":"Srikalahasti","description":"Drive to Srikalahasti — Srikalahasteeswara Temple (Air). Evening darshan. Overnight Tirupati area."},{"day":4,"title":"Chidambaram Departure","description":"Drive to Chidambaram — Nataraja Temple (Space). Darshan. Return Chennai for departure."}]',
 '[{"type":"standard","label":"Per Person","amount":7999},{"type":"group","label":"Group (4+) Per Head","amount":6499}]'),

-- 10. Kashi Gaya Prayagraj
('a0011010-0000-4000-8000-000000000010', '11111111-0001-0001-0001-000000000001', 'ff000001-0000-4000-8000-000000000001',
 'kashi-gaya-prayagraj-7d6n', 'Kashi Gaya Prayagraj Yatra', 'The Holy Trinity of North India — 7 Days / 6 Nights',
 'The most auspicious pilgrimage circuit of North India. Perform pitru tarpan at Gaya, seek moksha at Kashi Vishwanath, and take the holy dip at Triveni Sangam in Prayagraj.',
 7, 6, 15999, 'pilgrimage', true, true,
 'https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Vishnu Padam Temple Gaya','Pitru tarpan ceremony at Falgu River','Kashi Vishwanath VIP darshan','Ganga Aarti boat ride','Triveni Sangam holy dip'],
 ARRAY['6 nights accommodation','All meals','AC vehicle throughout','Experienced pilgrim guide','Pandit for rituals'],
 ARRAY['Train/flight to Gaya','Pooja samagri costs','Personal expenses'],
 '[{"day":1,"title":"Arrive Gaya","description":"Arrive Gaya. Check-in, rest. Evening visit Vishnupad Temple."},{"day":2,"title":"Gaya Pinda Daan","description":"Falgu River pinda daan ceremony. Visit Mangala Gauri, Brahmayoni Hill, Akshayavat."},{"day":3,"title":"Bodh Gaya Excursion","description":"Visit Bodh Gaya — Mahabodhi Temple (UNESCO), Bodhi Tree, Thai Monastery."},{"day":4,"title":"Gaya to Varanasi","description":"Drive to Varanasi. Check-in. Evening Ganga Aarti at Dashashwamedh Ghat."},{"day":5,"title":"Varanasi Darshan","description":"Dawn boat ride, Kashi Vishwanath darshan, Annapurna Temple, Kalbhairav Temple, Sarnath."},{"day":6,"title":"Varanasi to Prayagraj","description":"Drive to Prayagraj. Triveni Sangam, Allahabad Fort, Hanuman Temple, Akshayavat."},{"day":7,"title":"Prayagraj Departure","description":"Morning puja at Sangam. Transfer to airport/station for departure."}]',
 '[{"type":"standard","label":"Per Person (Twin Sharing)","amount":15999},{"type":"deluxe","label":"Deluxe Per Person","amount":21999}]'),

-- 11. Puri Bhubaneswar Konark
('a0011011-0000-4000-8000-000000000011', '11111111-0001-0001-0001-000000000001', 'd0010013-0000-4000-8000-000000000013',
 'puri-bhubaneswar-konark-5d4n', 'Puri Bhubaneswar Konark Tour', 'Odisha Sacred & Heritage Circuit — 5 Days / 4 Nights',
 'The Golden Triangle of Odisha — the sacred Jagannath Puri, the temple city of Bhubaneswar, and the magnificent Sun Temple at Konark. A perfect blend of spirituality and ancient architecture.',
 5, 4, 8999, 'pilgrimage', false, true,
 'https://images.pexels.com/photos/3573351/pexels-photo-3573351.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/3573351/pexels-photo-3573351.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Jagannath Puri Temple darshan','Konark Sun Temple UNESCO site','Lingaraja Temple Bhubaneswar','Puri Beach','Chilika Lake boat ride'],
 ARRAY['4 nights accommodation','Breakfast and dinner','AC vehicle','Expert guide','Temple arrangements'],
 ARRAY['Flight/train to Bhubaneswar','Personal expenses','Camera fees at Konark'],
 '[{"day":1,"title":"Arrive Bhubaneswar","description":"Arrive Bhubaneswar. Visit Lingaraja Temple, Mukteshwar Temple, Odisha State Museum."},{"day":2,"title":"Konark & Puri","description":"Morning Konark Sun Temple. Afternoon check-in Puri, Puri Beach."},{"day":3,"title":"Puri Jagannath","description":"Early morning Jagannath Temple darshan. Gundicha Temple, Swargadwar Beach, Chilika Lake."},{"day":4,"title":"Puri Local","description":"Raghurajpur artists village, Pipli applique market. Evening Puri Beach sunset."},{"day":5,"title":"Departure","description":"Morning Jagannath darshan. Transfer to Bhubaneswar airport."}]',
 '[{"type":"standard","label":"Per Person","amount":8999},{"type":"group","label":"Group Rate (4+)","amount":7499}]'),

-- 12. Haridwar Rishikesh
('a0011012-0000-4000-8000-000000000012', '11111111-0001-0001-0001-000000000001', 'd0010021-0000-4000-8000-000000000021',
 'haridwar-rishikesh-3d2n', 'Haridwar & Rishikesh Getaway', 'Gateway to the Gods — 3 Days / 2 Nights',
 'Experience the spiritual energy of Haridwar and Rishikesh — the gateway to the Himalayas. Attend the famous Ganga Aarti at Har Ki Pauri, practice yoga at ashrams, and feel the Himalayan river.',
 3, 2, 5999, 'pilgrimage', false, true,
 'https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Ganga Aarti at Har Ki Pauri','Laxman Jhula & Ram Jhula','Triveni Ghat sunrise','Ashram yoga session','River camping option available'],
 ARRAY['2 nights accommodation','Breakfast daily','AC vehicle','City guide'],
 ARRAY['Train/flight','Yoga class fees','River rafting charges','Personal expenses'],
 '[{"day":1,"title":"Arrive Haridwar","description":"Arrive Haridwar. Har Ki Pauri Ganga Aarti in the evening. Chandi Devi Temple, Mansa Devi Temple."},{"day":2,"title":"Rishikesh","description":"Drive to Rishikesh. Laxman Jhula, Ram Jhula, Parmarth Niketan, Beatles Ashram. Evening Aarti at Triveni Ghat."},{"day":3,"title":"Yoga & Departure","description":"Morning yoga session at riverside ashram. Neel Kanth Temple visit. Transfer for departure."}]',
 '[{"type":"standard","label":"Per Person","amount":5999},{"type":"couple","label":"Couple Package","amount":11499}]'),

-- 13. Amritsar Golden Temple
('a0011013-0000-4000-8000-000000000013', '11111111-0001-0001-0001-000000000001', 'd0010042-0000-4000-8000-000000000042',
 'amritsar-golden-temple-3d2n', 'Amritsar Golden Temple Tour', 'Harmandir Sahib & Wagah Border — 3 Days / 2 Nights',
 'A deeply moving visit to the Golden Temple, the holiest Sikh shrine, where spirituality meets magnificent architecture. Experience the langar, witness the Wagah Border ceremony, and feel the warm Punjabi hospitality.',
 3, 2, 6499, 'pilgrimage', false, true,
 'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Golden Temple amrit vela darshan','Langar community meal experience','Wagah Border Retreat ceremony','Jallianwala Bagh memorial','Durgiana Temple'],
 ARRAY['2 nights accommodation near Golden Temple','Breakfast daily','AC vehicle','Expert guide'],
 ARRAY['Flight/train to Amritsar','Personal shopping','Meals other than breakfast'],
 '[{"day":1,"title":"Arrive Amritsar","description":"Arrive Amritsar. Golden Temple evening visit. Participate in langar. Jallianwala Bagh memorial."},{"day":2,"title":"Full Day Amritsar","description":"Early morning Golden Temple (amrit vela). Durgiana Temple, Maharaja Ranjit Singh Museum. Afternoon Wagah Border ceremony."},{"day":3,"title":"Sightseeing Departure","description":"Local bazaar visit, Gobindgarh Fort. Transfer to airport for departure."}]',
 '[{"type":"standard","label":"Per Person","amount":6499},{"type":"couple","label":"Couple Package","amount":12499}]'),

-- 14. Mathura Vrindavan Agra
('a0011014-0000-4000-8000-000000000014', '11111111-0001-0001-0001-000000000001', 'd0010012-0000-4000-8000-000000000012',
 'mathura-vrindavan-agra-4d3n', 'Mathura Vrindavan & Agra Tour', 'Krishna Land + Taj Mahal — 4 Days / 3 Nights',
 'Walk in the footsteps of Lord Krishna in Mathura and Vrindavan, then marvel at the Taj Mahal in Agra. A divine and heritage combination package for a truly memorable North India journey.',
 4, 3, 7999, 'pilgrimage', false, true,
 'https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Krishna Janmasthan Temple Mathura','Banke Bihari Temple Vrindavan','Yamuna Aarti at Vishram Ghat','Taj Mahal at sunrise','Agra Fort & Fatehpur Sikri'],
 ARRAY['3 nights accommodation','Breakfast daily','AC vehicle','Professional guide'],
 ARRAY['Train/flight to Mathura','Taj Mahal entry fees','Personal expenses'],
 '[{"day":1,"title":"Arrive Mathura","description":"Arrive Mathura. Krishna Janmasthan Temple, Dwarkadhish Temple. Evening Yamuna Aarti at Vishram Ghat."},{"day":2,"title":"Vrindavan","description":"Banke Bihari Temple, ISKCON, Prem Mandir, Govardhan Hill parikrama."},{"day":3,"title":"Agra","description":"Drive to Agra. Taj Mahal at sunrise, Agra Fort, Itmad-ud-Daula, Mehtab Bagh sunset."},{"day":4,"title":"Departure","description":"Morning at leisure. Transfer to Agra/Mathura for departure."}]',
 '[{"type":"standard","label":"Per Person","amount":7999},{"type":"couple","label":"Couple Package","amount":15499}]'),

-- 15. Dvadasha Jyotirlinga
('a0011015-0000-4000-8000-000000000015', '11111111-0001-0001-0001-000000000001', 'd0010015-0000-4000-8000-000000000015',
 'dvadasha-jyotirlinga-12d11n', '12 Jyotirlinga Grand Yatra', 'Luxury Pilgrimage Across India — 12 Days / 11 Nights',
 'The grandest Shiva pilgrimage — visit all 12 sacred Jyotirlingas spread across India in one epic journey. Fly between locations for maximum comfort in our signature luxury pilgrimage experience.',
 12, 11, 49999, 'pilgrimage', true, true,
 'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['All 12 Jyotirlingas covered','Air-assisted between sectors','5-star accommodation','Personal pandit throughout','Abhishekam at each linga'],
 ARRAY['11 nights luxury accommodation','All meals included','Domestic flights between sectors','Personal pandit for rituals','Dedicated tour manager'],
 ARRAY['International flights','Personal expenses','Pooja samagri beyond package'],
 '[{"day":1,"title":"Somnath & Nageshwar","description":"Arrive Ahmedabad, drive to Somnath Jyotirlinga. Nageshwar Temple."},{"day":2,"title":"Somnath to Ujjain","description":"Fly to Indore. Mahakaleshwar Jyotirlinga, evening bhasma aarti."},{"day":3,"title":"Omkareshwar","description":"Drive to Omkareshwar island Jyotirlinga. Darshan and return."},{"day":4,"title":"Bhimashankar","description":"Fly to Pune. Drive Bhimashankar Jyotirlinga."},{"day":5,"title":"Trimbakeshwar & Grishneshwar","description":"Drive Nashik — Trimbakeshwar Jyotirlinga. Evening Grishneshwar."},{"day":6,"title":"Aundha Naganath","description":"Drive to Aundha Naganath, the ancient Jyotirlinga."},{"day":7,"title":"Parli Vaijnath","description":"Drive to Parli Vaijnath Jyotirlinga."},{"day":8,"title":"Srisailam Mallikarjuna","description":"Fly to Hyderabad. Drive Srisailam — Mallikarjuna Jyotirlinga."},{"day":9,"title":"Rameshwaram","description":"Fly to Madurai. Drive Rameshwaram — Ramanathaswamy Jyotirlinga."},{"day":10,"title":"Kashi Vishwanath","description":"Fly to Varanasi. Kashi Vishwanath Jyotirlinga. Ganga Aarti."},{"day":11,"title":"Kedarnath","description":"Fly to Dehradun. Helicopter to Kedarnath Jyotirlinga."},{"day":12,"title":"Departure","description":"Drive to Badrinath (bonus visit). Return Dehradun for departure."}]',
 '[{"type":"luxury","label":"Per Person All-inclusive Luxury","amount":49999},{"type":"ultra","label":"Ultra Luxury Private","amount":89999}]')
ON CONFLICT (slug) DO NOTHING;
