
-- Domestic, International, Honeymoon, Family, Adventure packages
INSERT INTO packages (id, category_id, destination_id, slug, title, subtitle, overview, duration_days, duration_nights, starting_price, tour_type, is_featured, is_published, cover_image, gallery, highlights, inclusions, exclusions, itinerary, pricing)
VALUES

-- DOMESTIC PACKAGES
('b0012001-0000-4000-8000-000000000001', '11111111-0001-0001-0001-000000000002', 'd0010039-0000-4000-8000-000000000039',
 'rajasthan-royal-circuit-7d6n', 'Rajasthan Royal Circuit', 'Jaipur Jodhpur Udaipur — 7 Days / 6 Nights',
 'Experience the royal splendor of Rajasthan across its three magnificent cities. From the Pink City''s palaces to Jodhpur''s blue-washed streets and Udaipur''s romantic lake palaces — this is India''s grandest journey.',
 7, 6, 18999, 'sightseeing', true, true,
 'https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Amber Fort & Hawa Mahal Jaipur','Mehrangarh Fort Jodhpur','Lake Pichola boat ride Udaipur','City Palace Udaipur','Camel safari at Sam Sand Dunes'],
 ARRAY['6 nights heritage accommodation','All breakfasts','AC vehicle throughout','Professional guide','All entry fees'],
 ARRAY['Airfare to Jaipur/from Udaipur','Dinners & lunches','Personal shopping'],
 '[{"day":1,"title":"Arrive Jaipur","description":"Arrive Jaipur, check-in at heritage hotel. Evening Chokhi Dhani folk dinner."},{"day":2,"title":"Jaipur City Tour","description":"Amber Fort, Hawa Mahal, City Palace, Jantar Mantar. Evening Johri Bazaar shopping."},{"day":3,"title":"Jaipur to Jodhpur","description":"Drive Jodhpur via Ajmer Pushkar. Evening Mehrangarh Fort at golden hour."},{"day":4,"title":"Jodhpur","description":"Mehrangarh Fort, Jaswant Thada, Umaid Bhawan. Explore blue city lanes."},{"day":5,"title":"Jodhpur to Udaipur","description":"Drive Udaipur via Ranakpur Jain Temples. Arrive, check-in."},{"day":6,"title":"Udaipur","description":"City Palace, Saheliyon ki Bari, Lake Pichola boat ride. Evening cultural show."},{"day":7,"title":"Departure","description":"Morning Jagdish Temple, Sajjangarh fort. Transfer to Udaipur airport."}]',
 '[{"type":"standard","label":"Per Person (Twin Sharing)","amount":18999},{"type":"deluxe","label":"Deluxe Per Person","amount":25999}]'),

('b0012002-0000-4000-8000-000000000002', '11111111-0001-0001-0001-000000000002', 'ff000009-0000-4000-8000-000000000009',
 'kerala-backwaters-honeymoon-5d4n', 'Kerala Backwaters & Hills', 'Munnar Alleppey Kovalam — 5 Days / 4 Nights',
 'Discover the serene beauty of God''s Own Country — misty tea gardens of Munnar, tranquil backwater cruises at Alleppey, and the golden sands of Kovalam. Kerala''s finest in one memorable journey.',
 5, 4, 13999, 'nature', true, true,
 'https://images.pexels.com/photos/2387416/pexels-photo-2387416.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2387416/pexels-photo-2387416.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Munnar tea garden walks','Houseboat stay in Alleppey backwaters','Kathakali performance','Kovalam beach sunset','Periyar wildlife spotting'],
 ARRAY['4 nights accommodation including houseboat','Breakfasts','AC vehicle','Guide','Houseboat cruise with meals'],
 ARRAY['Airfare to Kochi','Lunches & dinners outside houseboat','Personal expenses'],
 '[{"day":1,"title":"Arrive Kochi Munnar","description":"Arrive Kochi, drive Munnar. Tea Museum, Mattupetty Dam. Check-in hill resort."},{"day":2,"title":"Munnar","description":"Eravikulam National Park, Top Station, tea garden walk. Spice plantation tour."},{"day":3,"title":"Munnar to Alleppey","description":"Drive to Alleppey. Board houseboat. Backwater cruise through paddy fields and canals. Overnight on houseboat."},{"day":4,"title":"Alleppey to Kovalam","description":"Breakfast on houseboat. Drive to Kovalam. Evening beach time."},{"day":5,"title":"Kovalam Departure","description":"Morning beach walk. Lighthouse, Hawah Beach. Drive to Trivandrum airport."}]',
 '[{"type":"standard","label":"Per Person","amount":13999},{"type":"couple","label":"Couple Package","amount":26999}]'),

('b0012003-0000-4000-8000-000000000003', '11111111-0001-0001-0001-000000000002', 'd0010046-0000-4000-8000-000000000046',
 'leh-ladakh-adventure-7d6n', 'Leh Ladakh Adventure', 'Land of High Passes — 7 Days / 6 Nights',
 'Journey to the roof of the world — the breathtaking landscapes of Leh Ladakh. Navigate high-altitude passes, turquoise lakes, ancient Buddhist monasteries, and the mighty Zanskar River.',
 7, 6, 22999, 'adventure', false, true,
 'https://images.pexels.com/photos/1366957/pexels-photo-1366957.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1366957/pexels-photo-1366957.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Khardung La — world''s highest motorable road','Pangong Tso lake','Nubra Valley sand dunes','Thiksey & Hemis monasteries','Magnetic Hill & Sangam point'],
 ARRAY['6 nights accommodation','All meals','AC vehicle with driver','Oxygen cylinders','Inner Line Permit','Acclimatization support'],
 ARRAY['Airfare to Leh','Personal expenses','River rafting charges','Bike rental'],
 '[{"day":1,"title":"Arrive Leh","description":"Arrive Leh (3500m). Rest and acclimatization. Local market walk. Overnight Leh."},{"day":2,"title":"Leh Local Sightseeing","description":"Shanti Stupa, Leh Palace, Leh Market, Hall of Fame, Spituk Monastery. Short acclimatization walk."},{"day":3,"title":"Leh to Nubra Valley","description":"Cross Khardung La (5359m). Arrive Nubra Valley. Diskit Monastery, sand dunes, Bactrian camel ride."},{"day":4,"title":"Nubra to Pangong","description":"Drive via Shyok River to Pangong Tso Lake (4350m). Evening at lakeside."},{"day":5,"title":"Pangong to Leh","description":"Sunrise at Pangong. Drive back via Chang La pass. Hemis Monastery."},{"day":6,"title":"Leh Excursions","description":"Magnetic Hill, Gurudwara Patthar Sahib, Sangam Point (Indus-Zanskar confluence), Thiksey Monastery."},{"day":7,"title":"Departure","description":"Morning transfer to Leh Airport. Departure."}]',
 '[{"type":"standard","label":"Per Person (Twin Sharing)","amount":22999},{"type":"premium","label":"Premium Per Person","amount":29999}]'),

('b0012004-0000-4000-8000-000000000004', '11111111-0001-0001-0001-000000000002', 'd0010047-0000-4000-8000-000000000047',
 'goa-beach-holiday-4d3n', 'Goa Beach Holiday', 'Sun Sand Sea — 4 Days / 3 Nights',
 'The ultimate Goa beach escape! Explore the vibrant nightlife of North Goa, the peaceful beaches of South Goa, Portuguese colonial heritage, spice plantations, and the freshest seafood in India.',
 4, 3, 8999, 'beach', false, true,
 'https://images.pexels.com/photos/1007657/pexels-photo-1007657.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1007657/pexels-photo-1007657.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['North & South Goa beaches','Basilica of Bom Jesus (UNESCO)','Spice plantation tour','River cruise with live music','Old Goa Portuguese quarter'],
 ARRAY['3 nights beach resort stay','Daily breakfast','AC vehicle for transfers','Guide'],
 ARRAY['Airfare to Goa','Lunches & dinners','Water sports charges','Personal expenses'],
 '[{"day":1,"title":"Arrive Goa","description":"Arrive Goa airport, check-in. Evening Baga Beach, Tito''s Lane."},{"day":2,"title":"North Goa","description":"Fort Aguada, Calangute, Baga, Anjuna Flea Market, Chapora Fort, Vagator Beach."},{"day":3,"title":"South Goa & Heritage","description":"Old Goa churches (Basilica of Bom Jesus), Margao market, Colva & Palolem beaches. Sunset cruise."},{"day":4,"title":"Spice Plantation & Departure","description":"Morning spice plantation tour with Goan lunch. Transfer to airport."}]',
 '[{"type":"standard","label":"Per Person","amount":8999},{"type":"couple","label":"Couple Package","amount":16999}]'),

('b0012005-0000-4000-8000-000000000005', '11111111-0001-0001-0001-000000000002', 'ff000010-0000-4000-8000-000000000010',
 'andaman-island-5d4n', 'Andaman Island Paradise', 'Port Blair Havelock Neil — 5 Days / 4 Nights',
 'Dive into the pristine turquoise waters of the Andaman Islands. Explore the historic Cellular Jail, snorkel at Radhanagar Beach (Asia''s No.1 beach), and discover untouched coral reefs and tropical jungles.',
 5, 4, 16999, 'beach', true, true,
 'https://images.pexels.com/photos/1450363/pexels-photo-1450363.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1450363/pexels-photo-1450363.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Cellular Jail light & sound show','Radhanagar Beach — Asia''s No.1 Beach','Scuba diving & snorkeling','Neil Island coral reef','Glass bottom boat ride'],
 ARRAY['4 nights accommodation','Daily breakfast','All ferry transfers','All sightseeing with guide','Snorkeling equipment'],
 ARRAY['Airfare to Port Blair','Scuba diving charges','Personal expenses','Meals beyond breakfast'],
 '[{"day":1,"title":"Arrive Port Blair","description":"Arrive Port Blair. Cellular Jail tour, Sound & Light show. Check-in."},{"day":2,"title":"Port Blair to Havelock","description":"Ferry to Havelock Island. Radhanagar Beach (Beach 7). Afternoon Elephant Beach snorkeling."},{"day":3,"title":"Havelock","description":"Kalapathar Beach sunrise. Coral reef snorkeling. Afternoon leisure."},{"day":4,"title":"Havelock to Neil Island","description":"Ferry to Neil Island. Natural Bridge, Bharatpur Beach snorkeling. Return Port Blair."},{"day":5,"title":"Departure","description":"Chidiya Tapu (Sunset Point). Transfer to Port Blair airport."}]',
 '[{"type":"standard","label":"Per Person","amount":16999},{"type":"couple","label":"Couple Package","amount":32999}]'),

('b0012006-0000-4000-8000-000000000006', '11111111-0001-0001-0001-000000000002', 'd0010045-0000-4000-8000-000000000045',
 'manali-shimla-6d5n', 'Manali & Shimla Hill Tour', 'Himalayan Hill Stations — 6 Days / 5 Nights',
 'The classic Himachal Pradesh holiday! Experience the snow-capped peaks of Manali, the British-era charm of Shimla, Rohtang Pass adventure, and the alpine meadows of Solang Valley.',
 6, 5, 14999, 'hill-station', false, true,
 'https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Rohtang Pass (subject to permit)','Solang Valley snow activities','Hadimba Temple Manali','Mall Road Shimla','Kufri snow point'],
 ARRAY['5 nights accommodation','Daily breakfast','AC vehicle with driver','Guide'],
 ARRAY['Airfare/train to Chandigarh','Meals beyond breakfast','Snow activity charges','Personal expenses'],
 '[{"day":1,"title":"Arrive Manali","description":"Arrive Manali via Volvo bus/flight to Bhuntar. Check-in. Evening Mall Road."},{"day":2,"title":"Manali Sightseeing","description":"Hadimba Devi Temple, Vashisht hot springs, Tibetan Monastery, Old Manali."},{"day":3,"title":"Rohtang Pass","description":"Early morning Rohtang Pass (3978m) — snow play, photography. Afternoon Solang Valley."},{"day":4,"title":"Manali to Shimla","description":"Drive Shimla via Kullu, Pandoh Dam, Sundernagar. Check-in Shimla."},{"day":5,"title":"Shimla Sightseeing","description":"Mall Road, Jakhu Temple, Scandal Point, Christ Church, Kufri snow point."},{"day":6,"title":"Departure","description":"Morning at leisure. Transfer to Chandigarh airport/railway station."}]',
 '[{"type":"standard","label":"Per Person","amount":14999},{"type":"couple","label":"Couple Package","amount":28999}]'),

-- INTERNATIONAL PACKAGES
('c0013001-0000-4000-8000-000000000001', '11111111-0001-0001-0001-000000000003', 'b1d00008-0000-4000-8000-000000000008',
 'bali-indonesia-6d5n', 'Bali Magical Island', 'Temples Terraces & Sunsets — 6 Days / 5 Nights',
 'Experience the magic of Bali — mystical temples perched on clifftops, emerald rice terraces, sacred monkey forests, pristine beaches, and spectacular sunsets. A perfect tropical escape.',
 6, 5, 34999, 'international', true, true,
 'https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Tanah Lot Temple at sunset','Tegalalang Rice Terraces','Ubud Monkey Forest','Kecak Fire Dance','Seminyak & Kuta beaches'],
 ARRAY['5 nights villa/hotel accommodation','Daily breakfast','Private AC vehicle','English-speaking guide','All entry fees'],
 ARRAY['International airfare','Visa on arrival charges','Meals beyond breakfast','Personal expenses'],
 '[{"day":1,"title":"Arrive Bali","description":"Arrive Ngurah Rai Airport. Transfer to Ubud. Check-in, evening Kecak Fire Dance."},{"day":2,"title":"Ubud Culture","description":"Tegalalang Rice Terrace, Tirta Empul, Goa Gajah, Ubud Palace, Monkey Forest."},{"day":3,"title":"Ubud to Nusa Dua","description":"Besakih Temple (Mother Temple), Mount Batur sunrise option. Afternoon transfer to Nusa Dua beach."},{"day":4,"title":"Nusa Penida","description":"Day trip to Nusa Penida — Kelingking Beach (T-Rex cliff), Angel Billabong, Broken Beach."},{"day":5,"title":"Tanah Lot & Seminyak","description":"Tanah Lot sunset, Seminyak shopping and beach. Uluwatu Temple."},{"day":6,"title":"Departure","description":"Morning spa session. Transfer to airport for departure."}]',
 '[{"type":"standard","label":"Per Person (Twin Sharing)","amount":34999},{"type":"couple","label":"Couple Package","amount":67999}]'),

('c0013002-0000-4000-8000-000000000002', '11111111-0001-0001-0001-000000000003', 'ff000011-0000-4000-8000-000000000011',
 'thailand-budget-5d4n', 'Thailand Bangkok Pattaya', 'The Land of Smiles — 5 Days / 4 Nights',
 'Explore the vibrant contrasts of Thailand — the ornate temples and street food of Bangkok, and the beaches and nightlife of Pattaya. Affordable luxury in Southeast Asia.',
 5, 4, 29999, 'international', false, true,
 'https://images.pexels.com/photos/1450363/pexels-photo-1450363.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1450363/pexels-photo-1450363.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Grand Palace & Wat Phra Kaew','Floating Markets','Coral Island Pattaya','Alcazar Cabaret Show','Safari World Bangkok'],
 ARRAY['4 nights accommodation','Daily breakfast','Airport transfers','City tours with guide'],
 ARRAY['International airfare','Visa charges','Meals beyond breakfast','Personal shopping'],
 '[{"day":1,"title":"Arrive Bangkok","description":"Arrive Bangkok Suvarnabhumi. Transfer hotel. Evening Asiatique Night Market."},{"day":2,"title":"Bangkok City Tour","description":"Grand Palace, Wat Phra Kaew, Wat Pho (reclining Buddha), Wat Arun. Evening Chao Phraya dinner cruise."},{"day":3,"title":"Floating Market & Pattaya","description":"Damnoen Saduak Floating Market. Drive to Pattaya. Alcazar Show."},{"day":4,"title":"Pattaya","description":"Coral Island full-day trip — snorkeling, parasailing, banana boat. Evening Nong Nooch Garden."},{"day":5,"title":"Bangkok Departure","description":"Transfer to Bangkok airport. Siam Paragon shopping (if time permits). Departure."}]',
 '[{"type":"standard","label":"Per Person","amount":29999},{"type":"couple","label":"Couple Package","amount":57999}]'),

('c0013003-0000-4000-8000-000000000003', '11111111-0001-0001-0001-000000000003', 'ff000012-0000-4000-8000-000000000012',
 'dubai-luxury-4d3n', 'Dubai Luxury Escape', 'City of Gold & Records — 4 Days / 3 Nights',
 'Experience the ultimate luxury destination — the city of skyscrapers, golden deserts, and record-breaking attractions. From the world''s tallest tower to the pristine desert, Dubai dazzles at every turn.',
 4, 3, 39999, 'international', true, true,
 'https://images.pexels.com/photos/2044434/pexels-photo-2044434.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2044434/pexels-photo-2044434.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Burj Khalifa At The Top','Desert Safari with BBQ dinner','Dubai Frame','Dubai Mall & Fountain Show','Dhow Cruise Creek'],
 ARRAY['3 nights 4-star hotel','Daily breakfast','Airport transfers','City tour','Desert safari with BBQ','Dhow cruise with dinner'],
 ARRAY['International airfare','UAE visa charges','Meals beyond inclusions','Personal shopping'],
 '[{"day":1,"title":"Arrive Dubai","description":"Arrive Dubai airport. Check-in hotel. Evening Dhow Cruise Creek with dinner."},{"day":2,"title":"Dubai City Tour","description":"Burj Khalifa At The Top, Dubai Mall, Fountain Show, Dubai Frame. Afternoon Dubai Creek old city."},{"day":3,"title":"Desert Safari","description":"Morning at leisure. Afternoon Desert Safari — dune bashing, camel ride, sandboarding, BBQ dinner with cultural show."},{"day":4,"title":"Shopping & Departure","description":"Gold Souk, Spice Souk. Dubai Mall shopping. Transfer to airport."}]',
 '[{"type":"standard","label":"Per Person","amount":39999},{"type":"couple","label":"Couple Package","amount":77999}]'),

('c0013004-0000-4000-8000-000000000004', '11111111-0001-0001-0001-000000000003', 'b1d00007-0000-4000-8000-000000000007',
 'singapore-malaysia-7d6n', 'Singapore & Malaysia Tour', 'Twin City Adventure — 7 Days / 6 Nights',
 'The best of two modern Asian gems — the futuristic Gardens by the Bay in Singapore and the Twin Towers of Kuala Lumpur. Add in Genting Highlands and Batu Caves for a complete Southeast Asian adventure.',
 7, 6, 44999, 'international', false, true,
 'https://images.pexels.com/photos/1007657/pexels-photo-1007657.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1007657/pexels-photo-1007657.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Gardens by the Bay Night Safari','Universal Studios Singapore','Petronas Twin Towers','Genting Highlands casino resort','Batu Caves temple'],
 ARRAY['6 nights accommodation (3 each city)','Daily breakfast','Airport & city transfers','City tour guide'],
 ARRAY['International airfare','Singapore & Malaysia visa','Meals beyond breakfast','Theme park entry at Universal'],
 '[{"day":1,"title":"Arrive Singapore","description":"Arrive Singapore. Merlion Park, Clarke Quay. Check-in."},{"day":2,"title":"Singapore Attractions","description":"Gardens by the Bay, Marina Bay Sands, Cloud Forest, Flower Dome. Evening Light Show."},{"day":3,"title":"Universal Studios","description":"Full day Universal Studios Singapore. Evening Sentosa Beach."},{"day":4,"title":"Singapore to KL","description":"Drive to Kuala Lumpur. Batu Caves. Check-in KL."},{"day":5,"title":"Kuala Lumpur","description":"Petronas Twin Towers, KL Tower, Batu Caves (already seen), Central Market, Bukit Bintang."},{"day":6,"title":"Genting Highlands","description":"Full day Genting Highlands — theme park, casino. Return KL evening."},{"day":7,"title":"Departure","description":"Morning shopping Jalan Bukit Bintang. Transfer to KLIA for departure."}]',
 '[{"type":"standard","label":"Per Person","amount":44999},{"type":"couple","label":"Couple Package","amount":87999}]'),

-- HONEYMOON PACKAGES
('d0014001-0000-4000-8000-000000000001', '11111111-0001-0001-0001-000000000004', 'd0010053-0000-4000-8000-000000000053',
 'maldives-honeymoon-5d4n', 'Maldives Honeymoon Bliss', 'Overwater Villas & Coral Reefs — 5 Days / 4 Nights',
 'The most romantic destination on earth — pristine white beaches, crystal-clear lagoons, and luxurious overwater villas. The Maldives is the ultimate honeymoon paradise, offering unparalleled luxury and seclusion.',
 5, 4, 79999, 'international', true, true,
 'https://images.pexels.com/photos/1450363/pexels-photo-1450363.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1450363/pexels-photo-1450363.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Overwater villa with direct lagoon access','Private beach dining','Snorkeling with manta rays','Sunset dolphin cruise','Couple spa treatment'],
 ARRAY['4 nights overwater/water villa','All meals (full board)','Speedboat transfers','Snorkeling equipment','Sunset cruise','Couple spa 60 min'],
 ARRAY['International airfare','Male to resort seaplane','Premium alcohol','Diving courses','Personal expenses'],
 '[{"day":1,"title":"Arrive Maldives","description":"Arrive Male International Airport. Speedboat to resort. Welcome amenities, check-in."},{"day":2,"title":"Snorkeling & Spa","description":"House reef snorkeling. Afternoon couple spa. Sunset over Indian Ocean from deck."},{"day":3,"title":"Dolphin Cruise & Beach","description":"Morning dolphin watching cruise. Afternoon private beach time. Candlelit beach dinner."},{"day":4,"title":"Water Activities","description":"Kayaking, windsurfing, paddleboarding. Afternoon submarine / glass bottom boat."},{"day":5,"title":"Departure","description":"Last morning swim. Check-out. Speedboat to Male for departure."}]',
 '[{"type":"couple","label":"Couple Package (All-inclusive)","amount":79999},{"type":"premium","label":"Premium Overwater Villa","amount":119999}]'),

('d0014002-0000-4000-8000-000000000002', '11111111-0001-0001-0001-000000000004', 'd0010030-0000-4000-8000-000000000030',
 'kerala-honeymoon-5d4n', 'Kerala Romantic Escape', 'Munnar Thekkady Kumarakom — 5 Days / 4 Nights',
 'Romance blooms in God''s Own Country. Misty tea gardens, wildlife in the cardamom hills, and a magical houseboat glide through moonlit backwaters — Kerala crafts the perfect honeymoon.',
 5, 4, 22999, 'nature', true, true,
 'https://images.pexels.com/photos/2387416/pexels-photo-2387416.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2387416/pexels-photo-2387416.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Exclusive houseboat stay Kumarakom','Elephant interaction Thekkady','Munnar tea garden sunrise','Romantic candlelight dinner','Ayurvedic couple massage'],
 ARRAY['4 nights accommodation including houseboat','All meals on houseboat','AC vehicle','Guided wildlife safari','Ayurvedic massage (1 session each)'],
 ARRAY['Airfare to Kochi','Extra meals outside houseboat','Personal expenses'],
 '[{"day":1,"title":"Arrive Kochi Munnar","description":"Arrive Kochi. Drive to Munnar (130 km). Tea gardens en route. Check-in hill resort."},{"day":2,"title":"Munnar","description":"Eravikulam National Park, Top Station, Mattupetty Dam, Kundala Lake boating. Sunset dinner."},{"day":3,"title":"Munnar to Thekkady","description":"Periyar Wildlife Sanctuary boat ride. Elephant interaction. Spice garden visit."},{"day":4,"title":"Thekkady to Kumarakom","description":"Drive to Kumarakom backwaters. Board private houseboat. Overnight cruise."},{"day":5,"title":"Departure","description":"Breakfast on houseboat. Drive to Kochi airport for departure."}]',
 '[{"type":"couple","label":"Couple Package","amount":22999},{"type":"deluxe","label":"Deluxe Couple","amount":32999}]'),

-- FAMILY PACKAGES
('e0015001-0000-4000-8000-000000000001', '11111111-0001-0001-0001-000000000005', 'd0010039-0000-4000-8000-000000000039',
 'golden-triangle-family-6d5n', 'Golden Triangle Family Tour', 'Delhi Agra Jaipur — 6 Days / 5 Nights',
 'India''s most iconic journey for families — the Golden Triangle. Marvel at the Taj Mahal, explore Mughal forts, ride elephants at Amber, and discover the magic of Old Delhi. A journey your family will never forget.',
 6, 5, 17999, 'sightseeing', true, true,
 'https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Taj Mahal at sunrise','Amber Fort elephant ride','Red Fort & Qutub Minar Delhi','Rickshaw ride Old Delhi','Jaipur Pink City walk'],
 ARRAY['5 nights family rooms','Daily breakfast','AC vehicle for family','Professional guide','Taj Mahal entry'],
 ARRAY['Airfare to Delhi','Lunches & dinners','Personal expenses','Camera fees at Taj'],
 '[{"day":1,"title":"Arrive Delhi","description":"Arrive Delhi airport. Check-in. Evening Old Delhi — Jama Masjid, Chandni Chowk rickshaw ride."},{"day":2,"title":"Delhi Sightseeing","description":"Qutub Minar, Humayun Tomb, India Gate, Lotus Temple, Akshardham (evening)."},{"day":3,"title":"Delhi to Agra","description":"Drive Agra (3 hrs). Taj Mahal afternoon golden hour. Agra Fort."},{"day":4,"title":"Agra to Jaipur","description":"Taj Mahal sunrise. Drive Jaipur via Fatehpur Sikri. Check-in Jaipur."},{"day":5,"title":"Jaipur","description":"Amber Fort elephant ride, Hawa Mahal, City Palace, Jantar Mantar. Shopping."},{"day":6,"title":"Departure","description":"Morning Birla Temple, Central Park. Transfer to Jaipur airport."}]',
 '[{"type":"family","label":"Family Package (2 Adults + 2 Kids)","amount":17999},{"type":"standard","label":"Per Adult (Twin Sharing)","amount":17999}]'),

-- ADVENTURE PACKAGES
('f0016001-0000-4000-8000-000000000001', '11111111-0001-0001-0001-000000000006', 'd0010020-0000-4000-8000-000000000020',
 'rishikesh-adventure-3d2n', 'Rishikesh Adventure Camp', 'Rafting Bungee Camping — 3 Days / 2 Nights',
 'The adventure capital of India! Conquer the mighty Ganges with white-water rafting, take the leap on India''s highest bungee jump, zip-line over the river, and camp under the Himalayan stars.',
 3, 2, 7999, 'adventure', false, true,
 'https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=800',
 ARRAY['https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=800'],
 ARRAY['Grade 3-4 white water rafting 16km','Bungee jumping 83m India''s highest','Giant swing & flying fox','Riverside camping','Night bonfire & barbecue'],
 ARRAY['2 nights riverside camp accommodation','All meals','White water rafting 16km','All adventure activity charges','Safety equipment'],
 ARRAY['Train/flight to Haridwar/Dehradun','Transfers to Haridwar station','Personal expenses'],
 '[{"day":1,"title":"Arrive Camp","description":"Arrive Rishikesh. Transfer to riverside camp. Briefing. Evening cliff jumping and kayaking. Bonfire dinner."},{"day":2,"title":"Full Day Adventure","description":"Morning Grade 3-4 rafting (16km Marine Drive to Rishikesh). Afternoon bungee + giant swing + flying fox."},{"day":3,"title":"Yoga & Departure","description":"Morning yoga on the banks of Ganga. Breakfast. Transfer to Haridwar/Dehradun."}]',
 '[{"type":"standard","label":"Per Person","amount":7999},{"type":"group","label":"Group (6+) Per Person","amount":6499}]')

ON CONFLICT (slug) DO NOTHING;
